version: 2.1
jobs:
  compile:
   docker:
      - image: azrim89/kernel:latest
   steps:
      - run:
          command: |
            git config --global user.name "Fakeriz"
            git config --global user.email "i.fakeriz@outlook.com"
            git clone https://github.com/Coryanthes99/kernel_xiaomi_surya.git -b 6/test --depth=1
            cd kernel_xiaomi_surya
            bash /root/project/kernel_xiaomi_surya/compile.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
